---
- name: Obtener información sobre httpd
  hosts: redhat9
  gather_facts: true
  become: true

  tasks:
    - name: Verificar si httpd está instalado
      shell: rpm -qa | grep -i httpd || echo "No tiene instalado httpd"
      register: httpd_status

    - name: Imprimir resultados ordenados
      debug:
        msg: |
          Resultados de rpm -qa | grep -i httpd ordenados:
          {% for host in ansible_play_batch | sort(attribute='ansible_hostname') %}
          Hostname: {{ host }} / IP Address: {{ hostvars[host]['ansible_host'] }}
          Resultados de rpm -qa | grep -i httpd:
          {{ hostvars[host]['httpd_status']['stdout'] }}
          **************************
          {% endfor %}
