---
- name: Obtener información sobre httpd
  hosts: redhat9
  gather_facts: true
  become: true

  tasks:
    - name: Verificar si httpd está instalado
      shell: rpm -qa | grep -i httpd || echo "No tiene instalado httpd"
      register: httpd_status

    - name: Crear el directorio de informes si no existe
      local_action:
        module: file
        path: "/ansible/reportes/httpd/"
        state: directory

    - name: Generar informe
      local_action:
        module: copy
        content: |
          {% for host in play_hosts | sort %}
          Hostname: {{ hostvars[host]['ansible_host'] }} / IP Address: {{ hostvars[host]['ansible_host'] }}
          Resultados de rpm -qa | grep -i httpd:
          {{ hostvars[host]['httpd_status']['stdout'] | default('No está instalado httpd', true) }}
          **************************
          {% endfor %}
        dest: "/ansible/reportes/apache/informe.txt"
